import { Product, User } from './api';

export const mockProducts: Product[] = [
  {
    id: 1,
    title: 'Caftan Marocain Traditionnel',
    description: 'Magnifique caftan brodé main, tissu satin de haute qualité. Disponible en plusieurs couleurs.',
    price: 450,
    moq: 10,
    category: 'Mode & Textile',
    stock: 200,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 1,
      company_name: 'Textile Fès',
      city: 'Fès',
      verified: true,
    },
  },
  {
    id: 2,
    title: 'Huile d\'Argan Bio 100ml',
    description: 'Huile d\'argan cosmétique pure, pressée à froid. Certifiée biologique.',
    price: 85,
    moq: 50,
    category: 'Cosmétiques',
    stock: 500,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 2,
      company_name: 'Argan Essaouira',
      city: 'Essaouira',
      verified: true,
    },
  },
  {
    id: 3,
    title: 'Babouches Cuir Artisanales',
    description: 'Babouches en cuir véritable, fabriquées à Marrakech. Plusieurs pointures disponibles.',
    price: 120,
    moq: 24,
    category: 'Chaussures',
    stock: 300,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 3,
      company_name: 'Cuir Marrakech',
      city: 'Marrakech',
      verified: true,
    },
  },
  {
    id: 4,
    title: 'Tajine Céramique Décoré',
    description: 'Tajine traditionnel en terre cuite, décoration faite main. Idéal pour la cuisine.',
    price: 180,
    moq: 20,
    category: 'Artisanat',
    stock: 150,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 4,
      company_name: 'Poterie Safi',
      city: 'Safi',
      verified: true,
    },
  },
  {
    id: 5,
    title: 'Tapis Berbère Fait Main',
    description: 'Tapis berbère authentique tissé main par des coopératives du Haut Atlas.',
    price: 1200,
    moq: 5,
    category: 'Décoration',
    stock: 50,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 5,
      company_name: 'Artisanat Atlas',
      city: 'Ouarzazate',
      verified: true,
    },
  },
  {
    id: 6,
    title: 'Savon Noir Beldi 500g',
    description: 'Savon noir traditionnel marocain, 100% naturel, enrichi en huile d\'olive.',
    price: 45,
    moq: 100,
    category: 'Cosmétiques',
    stock: 1000,
    images: ['/placeholder.svg'],
    wholesaler: {
      id: 2,
      company_name: 'Argan Essaouira',
      city: 'Essaouira',
      verified: true,
    },
  },
];

export const mockPendingWholesalers: User[] = [
  {
    id: 10,
    email: 'contact@textile-casa.ma',
    role: 'WHOLESALER',
    status: 'PENDING',
    company_name: 'Textile Casablanca',
    city: 'Casablanca',
    phone_business: '+212 6 12 34 56 78',
  },
  {
    id: 11,
    email: 'info@ceramique-meknes.ma',
    role: 'WHOLESALER',
    status: 'PENDING',
    company_name: 'Céramique Meknès',
    city: 'Meknès',
    phone_business: '+212 6 98 76 54 32',
  },
];

export const moroccanCities = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Fès',
  'Tanger',
  'Agadir',
  'Meknès',
  'Oujda',
  'Kénitra',
  'Tétouan',
  'Safi',
  'El Jadida',
  'Nador',
  'Béni Mellal',
  'Essaouira',
  'Ouarzazate',
];

export const productCategories = [
  'Mode & Textile',
  'Cosmétiques',
  'Chaussures',
  'Artisanat',
  'Décoration',
  'Alimentation',
  'Électronique',
  'Bijoux',
  'Maroquinerie',
  'Épices',
];
